### PR TITLE
Force default texture if not found (+ Geode_ png support) + this sucks anyways and yall can prob do it better

### PR DESCRIPTION
**Pull request by MuhXd**

### CODE REVIEW

**Comment by matcool** [comment]
what is the purpose of this? the pr title is completely useless

**Comment by MuhXd** [comment]
It uhh makes it so if you don't have the texture (aka 2.2 texture)

**Comment by MuhXd** [comment]
So if you load a pack from 2.201 and not 2.206 it tries to add the missing textures

**Comment by altalk23** [comment]
i love uploading copyrighted material into an open source repository! hooray piracy!

even if you implement it properly this wouldnt get merged solely due to those textures being in history. so no.

**Comment by matcool** [comment]
adding onto this:
1. you cant just load fallback textures from somewhere else for things that are supposed to be in batch nodes
2. wtf is the point of "Geode_ png support"

**Pull request closed without merging**
